<?php

namespace AppBundle\Repository;

/**
 * Producto_fotosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Producto_fotosRepository extends \Doctrine\ORM\EntityRepository
{
}
